import type { Metadata, Viewport } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { PageRefresh } from '../components/refresh/page'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  appleWebApp: {
    statusBarStyle: 'black-translucent',
    capable: true,
  },
}

export const viewport: Viewport = {
  width: 'device-width',
  minimumScale: 1,
  maximumScale: 1,
  initialScale: 1,
  userScalable: false,
  viewportFit: 'cover',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-startup-image"
          href="https://alfaonline.servicecdn.ru/public/s3/static/newclick/pwa/splash-screens/1320x2868.png"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <PageRefresh>{children}</PageRefresh>
      </body>
    </html>
  )
}
